module.exports = [
    { name: 'Unknown', value: 'NULL' },
    { name: 'Armenia', value: 'AM' },
    { name: 'Belgium', value: 'BE' },
    { name: 'Canada', value: 'CA' },
    { name: 'Croatia', value: 'HR' },
    { name: 'Czechia', value: 'CZ' },
    { name: 'Denmark', value: 'DK' },
    { name: 'Estonia', value: 'EE' },
    { name: 'Finland', value: 'FI' },
    { name: 'France', value: 'FR' },
    { name: 'Germany', value: 'DE' },
    { name: 'Greece', value: 'GR' },
    { name: 'Hungary', value: 'HU' },
    { name: 'Latvia', value: 'LV' },
    { name: 'Netherlands', value: 'NL' },
    { name: 'Norway', value: 'NO' },
    { name: 'Poland', value: 'PL' },
    { name: 'Roamania', value: 'RO' },
    { name: 'Serbia', value: 'RS' },
    { name: 'Slovakia', value: 'SK' },
    { name: 'Slovenia', value: 'SI' },
    { name: 'Sweden', value: 'SE' },
    { name: 'Switzerland', value: 'CH' },
    { name: 'United Kingdom', value: 'GB' },
];
